version: "3.9"

services:
  api:
    container_name: api
    build:
      context: ./backend
      target: dev
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
